# Generated by Django 5.2.6 on 2025-10-10 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_type', models.SlugField(choices=[('course', 'training_provisioner.models.course.Course'), ('enrollment', 'training_provisioner.models.enrollment.Enrollment'), ('invalid_enrollment', 'training_provisioner.models.enrollment.InvalidEnrollment')], max_length=20)),
                ('csv_path', models.CharField(max_length=80, null=True)),
                ('csv_errors', models.TextField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=1)),
                ('override_sis_stickiness', models.BooleanField(default=False)),
                ('post_status', models.SmallIntegerField(null=True)),
                ('monitor_date', models.DateTimeField(null=True)),
                ('monitor_status', models.SmallIntegerField(null=True)),
                ('canvas_id', models.CharField(max_length=30, null=True)),
                ('canvas_state', models.CharField(max_length=80, null=True)),
                ('canvas_progress', models.SmallIntegerField(default=0)),
                ('canvas_warnings', models.TextField(null=True)),
                ('canvas_errors', models.TextField(null=True)),
            ],
            options={
                'db_table': 'import',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=20, unique=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('courses_changed_since_date', models.DateTimeField(null=True)),
                ('queue_id', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'term',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_id', models.CharField(db_index=True, max_length=8)),
                ('course_id', models.CharField(db_index=True, max_length=80)),
                ('section_id', models.CharField(max_length=80, null=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('enrollment_date', models.DateTimeField(null=True)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('priority', models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=1)),
                ('queue_id', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'enrollment',
                'unique_together': {('integration_id', 'course_id', 'section_id')},
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blueprint_canvas_course_id', models.IntegerField()),
                ('term_id', models.CharField(db_index=True, max_length=30)),
                ('account_id', models.CharField(max_length=80)),
                ('membership_type', models.SmallIntegerField(choices=[(0, 'title_vi')], default=0)),
                ('course_status', models.SmallIntegerField(choices=[(0, 'active'), (1, 'deleted'), (2, 'completed'), (3, 'published')], default=0)),
                ('is_provisioned', models.BooleanField(default=False)),
                ('course_count', models.IntegerField(default=0)),
                ('section_count', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'training_course',
                'unique_together': {('blueprint_canvas_course_id', 'term_id')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=80, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('provisioned_date', models.DateTimeField(null=True)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('priority', models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=0)),
                ('queue_id', models.CharField(max_length=30, null=True)),
                ('training_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_provisioner.trainingcourse')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
