# Generated by Django 5.2.6 on 2025-11-14 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('course_ordinal', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('provisioned_date', models.DateTimeField(null=True)),
                ('provisioned_error', models.BooleanField(null=True)),
                ('provisioned_status', models.CharField(max_length=512, null=True)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('priority', models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=1)),
                ('queue_id', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_type', models.SlugField(choices=[('course', 'training_provisioner.models.course.Course'), ('section', 'training_provisioner.models.section.Section'), ('enrollment', 'training_provisioner.models.enrollment.Enrollment')], max_length=20)),
                ('csv_path', models.CharField(max_length=80, null=True)),
                ('csv_errors', models.TextField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=1)),
                ('override_sis_stickiness', models.BooleanField(default=False)),
                ('post_status', models.SmallIntegerField(null=True)),
                ('monitor_date', models.DateTimeField(null=True)),
                ('monitor_status', models.SmallIntegerField(null=True)),
                ('canvas_id', models.CharField(max_length=30, null=True)),
                ('canvas_state', models.CharField(max_length=80, null=True)),
                ('canvas_progress', models.SmallIntegerField(default=0)),
                ('canvas_warnings', models.TextField(null=True)),
                ('canvas_errors', models.TextField(null=True)),
            ],
            options={
                'db_table': 'import',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=80, null=True)),
                ('section_ordinal', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('provisioned_date', models.DateTimeField(null=True)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('priority', models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=1)),
                ('queue_id', models.CharField(max_length=30, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_provisioner.course')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('blueprint_course_id', models.CharField(max_length=100)),
                ('term_id', models.CharField(db_index=True, max_length=30)),
                ('account_id', models.CharField(max_length=80)),
                ('membership_type', models.SmallIntegerField(choices=[(0, 'test_membership'), (1, 'title_vi_membership'), (2, 'title_vi_booster_membership')], default=0)),
                ('course_status', models.SmallIntegerField(choices=[(0, 'active'), (1, 'deleted'), (2, 'completed'), (3, 'published')], default=0)),
                ('is_provisioned', models.BooleanField(default=False)),
                ('course_count', models.IntegerField(default=0)),
                ('section_count', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_course',
                'unique_together': {('blueprint_course_id', 'term_id')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='training_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_provisioner.trainingcourse'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_id', models.CharField(db_index=True, max_length=8)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('provisioned_date', models.DateTimeField(null=True)),
                ('deleted_date', models.DateTimeField(null=True)),
                ('priority', models.SmallIntegerField(choices=[(0, 'none'), (1, 'normal'), (2, 'high'), (3, 'immediate')], default=1)),
                ('queue_id', models.CharField(max_length=30, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_provisioner.course')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training_provisioner.section')),
            ],
            options={
                'db_table': 'enrollment',
                'unique_together': {('integration_id', 'course', 'section')},
            },
        ),
    ]
