# Generated by Django 5.2.6 on 2025-12-03 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_provisioner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='course_count',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='section_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
