# Generated by Django 5.2.6 on 2025-12-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_provisioner', '0002_alter_trainingcourse_course_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcourse',
            name='course_type',
            field=models.CharField(choices=[('101', 'Title VI 101 Course'), ('booster', 'Title VI Booster Course')], default='101', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='membership_type',
            field=models.SmallIntegerField(choices=[(0, 'test_membership'), (1, 'title_vi_membership_candidates'), (2, 'title_vi_booster_membership_candidates')], default=0),
        ),
    ]
