# Generated by Django 5.2.6 on 2025-12-16 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_provisioner', '0003_trainingcourse_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcourse',
            name='account_id',
            field=models.CharField(help_text='Each course will be created in this account SIS ID.', max_length=80),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='blueprint_course_id',
            field=models.CharField(help_text='Each course will based on this blueprint course SIS ID.', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='course_count',
            field=models.IntegerField(default=1, help_text='Number of courses to provision from blueprint course.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='course_name',
            field=models.CharField(help_text='Name given to each provisioned course.', max_length=200),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='course_status',
            field=models.SmallIntegerField(choices=[(0, 'active'), (1, 'deleted'), (2, 'completed'), (3, 'published')], default=0, help_text='Canvas course status applied to each course'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='is_provisioned',
            field=models.BooleanField(default=False, help_text='Check to provision courses to canvas. Uncheck will not remove courses from canvas.'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='section_count',
            field=models.IntegerField(default=0, help_text='Number of sections within each course to enroll students.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='term_id',
            field=models.CharField(db_index=True, help_text='Each course will be assigned this term SIS ID.', max_length=30),
        ),
    ]
