# Generated by Django 5.2.6 on 2026-02-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_provisioner', '0004_alter_trainingcourse_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='eligible_terms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
