# Generated by Django 5.2.6 on 2026-02-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_provisioner', '0005_enrollment_eligible_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentHistoryEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Enrollment Created'), ('updated', 'Enrollment Updated'), ('deleted', 'Enrollment Deleted'), ('reactivated', 'Enrollment Reactivated')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('integration_id', models.CharField(db_index=True, max_length=8)),
                ('course_id', models.CharField(max_length=100)),
                ('section_id', models.CharField(blank=True, max_length=100, null=True)),
                ('eligible_terms', models.JSONField(blank=True, default=list)),
                ('previous_eligible_terms', models.JSONField(blank=True, default=list, help_text='Previous eligible terms before update (for update events)', null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_events', to='training_provisioner.enrollment')),
            ],
            options={
                'db_table': 'enrollment_history_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['integration_id', 'timestamp'], name='enrollment__integra_c2b5e6_idx'), models.Index(fields=['event_type', 'timestamp'], name='enrollment__event_t_fc9301_idx'), models.Index(fields=['course_id', 'timestamp'], name='enrollment__course__d80615_idx')],
            },
        ),
    ]
