# Generated by Django 5.2.6 on 2026-02-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_provisioner', '0006_enrollmenthistoryevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
