# Generated by Django 5.2.6 on 2026-02-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_provisioner', '0007_alter_enrollment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmenthistoryevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Enrollment Created'), ('updated', 'Enrollment Updated'), ('deleted', 'Enrollment Deleted'), ('moved', 'Enrollment Moved'), ('reactivated', 'Enrollment Reactivated')], db_index=True, max_length=20),
        ),
    ]
